// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJwtMvioxVIjjhLxvCE-Tm7H8dSmV3B7I',
    appId: '1:545065041992:web:5cbfa5574f3ec90337d87d',
    messagingSenderId: '545065041992',
    projectId: 'act13-793bf',
    authDomain: 'act13-793bf.firebaseapp.com',
    storageBucket: 'act13-793bf.firebasestorage.app',
    measurementId: 'G-S1ZYD6GNZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAIXjd9tbDlPIqXK4xzMuScARcQp9yung',
    appId: '1:545065041992:android:ff25e7cd44f783fd37d87d',
    messagingSenderId: '545065041992',
    projectId: 'act13-793bf',
    storageBucket: 'act13-793bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoFgnuZcjJ_7hlfCKhtB7rGRBw4Mch4wQ',
    appId: '1:545065041992:ios:962904bf23a0246737d87d',
    messagingSenderId: '545065041992',
    projectId: 'act13-793bf',
    storageBucket: 'act13-793bf.firebasestorage.app',
    iosBundleId: 'com.example.act13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoFgnuZcjJ_7hlfCKhtB7rGRBw4Mch4wQ',
    appId: '1:545065041992:ios:962904bf23a0246737d87d',
    messagingSenderId: '545065041992',
    projectId: 'act13-793bf',
    storageBucket: 'act13-793bf.firebasestorage.app',
    iosBundleId: 'com.example.act13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJwtMvioxVIjjhLxvCE-Tm7H8dSmV3B7I',
    appId: '1:545065041992:web:d8c47216bf0a00a837d87d',
    messagingSenderId: '545065041992',
    projectId: 'act13-793bf',
    authDomain: 'act13-793bf.firebaseapp.com',
    storageBucket: 'act13-793bf.firebasestorage.app',
    measurementId: 'G-KLY7H1TZYC',
  );
}
